version: '3.4'

services:
  webapi:
    image: ${DOCKER_REGISTRY-}webapi
    build:
      context: .
      dockerfile: WebApi/Dockerfile

  redis:
    image: redis:latest
    volumes:
      - redis-data:/data
    ports:
      - 6379:6379

volumes:
  redis-data: